# Generated by Django 3.2 on 2021-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=200)),
                ('website_url', models.CharField(max_length=200)),
                ('portfolio', models.ManyToManyField(to='jobboard.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('crawl_date', models.DateTimeField(verbose_name='date of the crawl')),
                ('country', models.CharField(max_length=100)),
                ('offer_url', models.CharField(max_length=600)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobboard.startup')),
            ],
        ),
    ]
