# Generated by Django 3.2 on 2021-06-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0003_rename_startup_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='vc_website_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
