# Generated by Django 3.2 on 2021-06-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0004_portfolio_vc_website_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
