# Generated by Django 3.2 on 2021-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0006_auto_20210604_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startup',
            name='sector',
            field=models.CharField(choices=[('N', '-'), ('B2BO', 'B2B Services / Operation'), ('CONS', 'Consumer'), ('DATA', 'Data'), ('HEAL', 'Health'), ('INSU', 'InsurTech'), ('NEWI', 'New Infrastructure / Computing'), ('SAAS', 'SaaS'), ('TECH', 'Tech')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='crawl_date',
            field=models.DateTimeField(verbose_name='Date of the crawl'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('N', '-'), ('S', 'Seed'), ('A', 'Series A'), ('B', 'Series B'), ('C', 'Series C')], default='N', max_length=100),
        ),
    ]
