# Generated by Django 3.2 on 2021-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0007_auto_20210604_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='sector',
            field=models.CharField(choices=[('N', '-'), ('B2BO', 'B2B Services / Operation'), ('CONS', 'Consumer'), ('DATA', 'Data'), ('HEAL', 'Health'), ('INSU', 'InsurTech'), ('NEWI', 'New Infrastructure / Computing'), ('SAAS', 'SaaS'), ('TECH', 'Tech'), ('O', 'Other')], default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('N', '-'), ('S', 'Seed'), ('A', 'Series A'), ('B', 'Series B'), ('C', 'Series C'), ('O', 'Other')], default='N', max_length=100),
        ),
    ]
