# Generated by Django 3.2 on 2021-06-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0009_auto_20210604_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company')),
                ('logo', models.ImageField(max_length=200, upload_to=None, verbose_name='Logo')),
                ('stage', models.CharField(choices=[('N', '-'), ('S', 'Seed'), ('A', 'Series A'), ('B', 'Series B'), ('C', 'Series C'), ('O', 'Other')], default='N', max_length=100, verbose_name='Stage')),
                ('sector', models.CharField(choices=[('N', '-'), ('B2BO', 'B2B Services / Operation'), ('CONS', 'Consumer'), ('DATA', 'Data'), ('HEAL', 'Health'), ('INSU', 'InsurTech'), ('NEWI', 'New Infrastructure / Computing'), ('SAAS', 'SaaS'), ('TECH', 'Tech'), ('O', 'Other')], default='N', max_length=100, verbose_name='Sector')),
                ('company_website_url', models.CharField(max_length=200, verbose_name='Website')),
                ('scraping_source_url', models.CharField(max_length=200, verbose_name='Syncing source:')),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobboard.company'),
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
