# Generated by Django 3.2 on 2021-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0010_auto_20210604_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scraping_source_url',
            field=models.CharField(max_length=1000, verbose_name='Syncing source:'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='crawl_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of the crawl'),
        ),
        migrations.AlterField(
            model_name='job',
            name='offer_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Offer Link'),
        ),
    ]
