# Generated by Django 3.2 on 2021-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0012_alter_job_crawl_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
