# Generated by Django 3.2 on 2021-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0014_alter_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='offer_url',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='Offer Link'),
        ),
    ]
