# Generated by Django 3.2 on 2021-07-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobboard', '0015_alter_job_offer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobboard.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='offer_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Offer Link'),
        ),
    ]
